/* بيانات مكتبة الأفاعي الغير معروفة في إسرائيل — 19 نوعًا غير سام */
const unknownData = [
  { latin:"Psammophis aegyptius", img:"images/unk-01-psammophis-aegyptius.jpg",
    name:{ ar:"الحية المصرية رباعية الخطوط", he:"ארבע־קו מצרי", en:"Egyptian Four-lined Snake" },
    desc:{ ar:"ثعبان طويل ونحيل، يحمل أربعة خطوط داكنة تمتدّ على طول جسمه.",
           he:"נחש ארוך ודק, בעל ארבעה קווים כהים לאורך הגוף.",
           en:"A long, slender snake bearing four dark stripes running the length of its body." },
    length:{ ar:"حتى نحو 120 سم", he:"עד כ־120 ס\"מ", en:"Up to ~120 cm" },
    diet:{ ar:"أساسًا السحالي، وكذلك القوارض الصغيرة ومفصليات الأرجل", he:"בעיקר לטאות, וכן מכרסמים קטנים ופרוקי־רגליים", en:"Mainly lizards, plus small rodents and arthropods" },
    range:{ ar:"مناطق صحراوية وقاحلة في إسرائيل، خاصّة غور الأردن والمناطق الجنوبية", he:"אזורים מדבריים וצחיחים בישראל, בעיקר בבקעת הירדן ובאזורים הדרומיים", en:"Desert and arid regions in Israel, mainly the Jordan Valley and southern areas" } },

  { latin:"Platyceps saharicus", img:"images/unk-02-platyceps-saharicus.jpg",
    name:{ ar:"ثعبان الصحراء النحيل", he:"זעמן דק", en:"Saharan Racer" },
    desc:{ ar:"حنش نحيل وسريع الحركة، غير سام، من فصيلة الأحناش.",
           he:"זעמן דק וזריז, לא ארסי, ממשפחת הזעמניים.",
           en:"A slender, fast-moving racer of the Colubridae family — non-venomous." },
    length:{ ar:"حتى نحو 120–140 سم", he:"עד כ־120–140 ס\"מ", en:"Up to ~120–140 cm" },
    diet:{ ar:"قوارض صغيرة وسحالي ومفصليات الأرجل", he:"מכרסמים קטנים, לטאות ופרוקי־רגליים", en:"Small rodents, lizards, and arthropods" },
    range:{ ar:"مناطق صحراوية في جنوب إسرائيل: النقب والعربة وغور الأردن", he:"בעיקר באזורים מדבריים בדרום ישראל, בנגב, בערבה ובבקעת הירדן", en:"Mainly desert areas of southern Israel: the Negev, the Arava, and the Jordan Valley" } },

  { latin:"Platyceps elegantissimus", img:"images/unk-03-platyceps-elegantissimus.jpg",
    name:{ ar:"الثعبان الأنيق", he:"זעמן יפהפה", en:"Elegant Racer" },
    desc:{ ar:"ثعبان غير سام ونادر نسبيًا في إسرائيل.",
           he:"נחש לא ארסי ונדיר יחסית בישראל.",
           en:"A non-venomous snake, relatively rare in Israel." },
    length:{ ar:"حتى نحو 100 سم", he:"עד כ־100 ס\"מ", en:"Up to ~100 cm" },
    diet:{ ar:"أساسًا السحالي والثعابين الصغيرة", he:"בעיקר לטאות ונחשים קטנים", en:"Mainly lizards and small snakes" },
    range:{ ar:"موائل صحراوية، خاصّة منطقة العربة وجنوب إسرائيل", he:"בתי גידול מדבריים, בעיקר באזור הערבה ובדרום ישראל", en:"Desert habitats, mainly the Arava region and southern Israel" } },

  { latin:"Platyceps sinai", img:"images/unk-04-platyceps-sinai.jpg",
    name:{ ar:"ثعبان سيناء المخطط", he:"זעמן סיני", en:"Sinai Racer" },
    desc:{ ar:"ثعبان صغير نحيل ورشيق، بنمط من الحلقات والأشرطة الداكنة.",
           he:"נחש קטן, דק וזריז, בעל דגם של טבעות ופסים כהים.",
           en:"A small, slender and agile snake with a pattern of dark rings and bands." },
    length:{ ar:"حتى نحو 60 سم", he:"עד כ־60 ס\"מ", en:"Up to ~60 cm" },
    diet:{ ar:"أساسًا السحالي ومفصليات الأرجل الصغيرة", he:"בעיקר לטאות ופרוקי־רגליים קטנים", en:"Mainly lizards and small arthropods" },
    range:{ ar:"جنوب النقب والعربة وجبال إيلات وصحراء يهودا", he:"דרום הנגב, הערבה, הרי אילת ומדבר יהודה", en:"Southern Negev, the Arava, Eilat mountains, and the Judean Desert" } },

  { latin:"Zamenis hohenackeri", img:"images/unk-05-zamenis-hohenackeri.jpg",
    name:{ ar:"أفعى الفئران عبر القوقاز", he:"כרכן חלק", en:"Transcaucasian Ratsnake" },
    desc:{ ar:"في إسرائيل تتركّز هذه الأفعى أساسًا في منطقة جبل الشيخ (الحرمون).",
           he:"בישראל מדובר באוכלוסייה המצויה בעיקר באזור החרמון.",
           en:"In Israel its population is found mainly in the Mount Hermon area." },
    length:{ ar:"حتى نحو 90 سم", he:"עד כ־90 ס\"מ", en:"Up to ~90 cm" },
    diet:{ ar:"قوارض صغيرة وأحيانًا زواحف", he:"מכרסמים קטנים ולעיתים גם זוחלים", en:"Small rodents and occasionally reptiles" },
    range:{ ar:"الحرمون وشمال هضبة الجولان", he:"החרמון וצפון רמת הגולן", en:"Hermon and northern Golan Heights" } },

  { latin:"Elaphe druzei", img:"images/unk-06-elaphe-druzei.jpg",
    name:{ ar:"ثعبان الفئران رباعي الخطوط", he:"כרכן קרינים", en:"Four-lined Ratsnake" },
    desc:{ ar:"من أكبر أفاعي المنطقة؛ صُنّف سكّان إسرائيل سابقًا ضمن Elaphe quatuorlineata وE. sauromates.",
           he:"מהנחשים הגדולים באזור; בעבר סווגה אוכלוסיית ישראל תחת Elaphe quatuorlineata ו־E. sauromates.",
           en:"One of the region's largest snakes; Israel's population was formerly classified under Elaphe quatuorlineata and E. sauromates." },
    length:{ ar:"حتى نحو 2.2 متر", he:"עד כ־2.2 מטרים", en:"Up to ~2.2 meters" },
    diet:{ ar:"قوارض وطيور وبيوض وزواحف", he:"מכרסמים, ציפורים, ביצים וזוחלים", en:"Rodents, birds, eggs, and reptiles" },
    range:{ ar:"في إسرائيل أساسًا في الحرمون وشمال الجولان", he:"בישראל בעיקר בחרמון ובצפון הגולן", en:"In Israel, mainly the Hermon and northern Golan" } },

  { latin:"Micrelaps muelleri", img:"images/unk-07-micrelaps-muelleri.jpg",
    name:{ ar:"الثعبان المرجاني الكاذب ثنائي اللون", he:"מחרוזן הטבעות", en:"Mueller's False Coral Snake" },
    desc:{ ar:"ثعبان صغير بأشرطة سوداء وصفراء إلى بيضاء. (خلفي الأنياب بسمّ خفيف غير خطر على الإنسان.)",
           he:"נחש קטן בעל פסים שחורים וצהובים עד לבנים.",
           en:"A small snake with black and yellow-to-white banding. (Rear-fanged with weak venom, harmless to humans.)" },
    length:{ ar:"حتى نحو 60 سم، وغالبًا أقل", he:"עד כ־60 ס\"מ, בדרך כלל פחות", en:"Up to ~60 cm, usually less" },
    diet:{ ar:"أساسًا الثعابين الصغيرة والزواحف", he:"בעיקר נחשים קטנים וזוחלים", en:"Mainly small snakes and reptiles" },
    range:{ ar:"من شمال إسرائيل حتى منطقة بئر السبع، وكذلك غور الأردن والمناطق المجاورة شرقًا", he:"מצפון ישראל ועד אזור באר שבע, וכן בבקעת הירדן ובאזורים סמוכים במזרח", en:"From northern Israel to the Beer Sheva area, plus the Jordan Valley and nearby eastern regions" } },

  { latin:"Lytorhynchus diadema", img:"images/unk-08-lytorhynchus-diadema.jpg",
    name:{ ar:"ثعبان الرمال ذو الإكليل", he:"נחש־חולות חרטומן", en:"Diademed Sand Snake" },
    desc:{ ar:"ثعبان صغير متكيّف جيّدًا للعيش في الرمال والحفر في التربة الرخوة.",
           he:"נחש קטן המותאם היטב לחיים בחול ולחפירה בקרקע רכה.",
           en:"A small snake well adapted to life in sand and to burrowing in soft soil." },
    length:{ ar:"حتى نحو 50–60 سم", he:"עד כ־50–60 ס\"מ", en:"Up to ~50–60 cm" },
    diet:{ ar:"أساسًا السحالي الصغيرة ومفصليات الأرجل", he:"בעיקר לטאות קטנות ופרוקי־רגליים", en:"Mainly small lizards and arthropods" },
    range:{ ar:"مناطق رملية في إسرائيل، من رمال السهل الساحلي حتى المناطق الصحراوية جنوبًا", he:"אזורים חוליים בישראל, מחולות מישור החוף ועד אזורים מדבריים בדרום", en:"Sandy areas in Israel, from coastal-plain dunes to southern desert regions" } },

  { latin:"Macroprotodon cucullatus", img:"images/unk-09-macroprotodon-cucullatus.jpg",
    name:{ ar:"ثعبان القلنسوة", he:"נחש כיפה", en:"False Smooth Snake" },
    desc:{ ar:"اسمه مستمدّ من البقعة الداكنة على رأسه التي تشبه القلنسوة.",
           he:"שמו נובע מהכתם הכהה שעל ראשו, המזכיר כיפה.",
           en:"Named for the dark patch on its head that resembles a cap (hood)." },
    length:{ ar:"حتى نحو 55 سم", he:"עד כ־55 ס\"מ", en:"Up to ~55 cm" },
    diet:{ ar:"أساسًا السحالي الصغيرة", he:"בעיקר לטאות קטנות", en:"Mainly small lizards" },
    range:{ ar:"مناطق رملية، خاصّة جنوب السهل الساحلي وغرب النقب", he:"אזורים חוליים, בעיקר במישור החוף הדרומי ובנגב המערבי", en:"Sandy areas, mainly the southern coastal plain and western Negev" } },

  { latin:"Leptotyphlops macrorhynchus", img:"images/unk-10-leptotyphlops-macrorhynchus.jpg",
    name:{ ar:"الثعبان الأعمى دقيق الجسم", he:"נימון דק", en:"Hook-billed Blind Snake" },
    desc:{ ar:"ثعبان دقيق جدًا صغير الحجم، يقضي معظم وقته تحت سطح الأرض.",
           he:"זהו נחש זעיר, דק מאוד וחי ברוב זמנו מתחת לפני הקרקע.",
           en:"A tiny, very slender snake that spends most of its time below ground." },
    length:{ ar:"عادةً نحو 20–30 سم", he:"בדרך כלל כ־20–30 ס\"מ", en:"Usually ~20–30 cm" },
    diet:{ ar:"أساسًا النمل والنمل الأبيض والحشرات الصغيرة", he:"בעיקר נמלים, טרמיטים וחרקים קטנים", en:"Mainly ants, termites, and small insects" },
    range:{ ar:"في إسرائيل: صحراء يهودا وغور الأردن والبحر الميت والنقب والعربة", he:"בישראל: מדבר יהודה, בקעת הירדן, ים המלח, הנגב והערבה", en:"In Israel: the Judean Desert, Jordan Valley, Dead Sea, Negev, and Arava" } },

  { latin:"Telescopus dhara", img:"images/unk-11-telescopus-dhara.jpg",
    name:{ ar:"ثعبان القط الأحمر", he:"עין־חתול אדמדם", en:"Tropical Cat Snake" },
    desc:{ ar:"ثعبان خلفي الأنياب بسمّ خفيف، نشِط أساسًا في ساعات الليل.",
           he:"נחש תת־ארסי הפעיל בעיקר בשעות הלילה.",
           en:"A mildly (rear-fanged) venomous snake, active mainly at night." },
    length:{ ar:"حتى نحو 120 سم", he:"עד כ־120 ס\"מ", en:"Up to ~120 cm" },
    diet:{ ar:"أساسًا السحالي والوزغ وأحيانًا القوارض الصغيرة", he:"בעיקר לטאות, שממיות ולעיתים מכרסמים קטנים", en:"Mainly lizards, geckos, and occasionally small rodents" },
    range:{ ar:"مناطق صحراوية في جنوب إسرائيل", he:"אזורים מדבריים בדרום ישראל", en:"Desert areas in southern Israel" } },

  { latin:"Telescopus hoogstraali", img:"images/unk-12-telescopus-hoogstraali.jpg",
    name:{ ar:"ثعبان القط الرمادي", he:"עין־חתול אפור", en:"Grey Cat Snake" },
    desc:{ ar:"ثعبان خلفي الأنياب بسمّ خفيف ونادر نسبيًا، لونه رمادي ورأسه داكن.",
           he:"נחש תת־ארסי ונדיר יחסית, בעל צבע אפור וראש כהה.",
           en:"A mildly (rear-fanged) venomous and relatively rare snake, grey with a dark head." },
    length:{ ar:"حتى نحو 100 سم", he:"עד כ־100 ס\"מ", en:"Up to ~100 cm" },
    diet:{ ar:"أساسًا السحالي والقوارض الصغيرة", he:"בעיקר לטאות ומכרסמים קטנים", en:"Mainly lizards and small rodents" },
    range:{ ar:"وسط وجنوب النقب", he:"מרכז ודרום הנגב", en:"Central and southern Negev" } },

  { latin:"Rhynchocalamus melanocephalus", img:"images/unk-13-rhynchocalamus-melanocephalus.jpg",
    name:{ ar:"ثعبان أسود الرأس", he:"שחור־ראש", en:"Palestine Black-headed Snake" },
    desc:{ ar:"ثعبان صغير غير سام، يسهل تمييزه برأسه الأسود.",
           he:"נחש קטן ולא ארסי, שקל לזהותו בזכות ראשו השחור.",
           en:"A small, non-venomous snake, easily recognized by its black head." },
    length:{ ar:"عادةً نحو 30–50 سم", he:"בדרך כלל כ־30–50 ס\"מ", en:"Usually ~30–50 cm" },
    diet:{ ar:"أساسًا مفصليات الأرجل والزواحف الصغيرة", he:"בעיקר פרוקי־רגליים וזוחלים קטנים", en:"Mainly arthropods and small reptiles" },
    range:{ ar:"منتشر في أنحاء إسرائيل: من الجليل والحرمون شمالًا، مرورًا بصحراء يهودا وغور الأردن، وحتى النقب جنوبًا", he:"נפוץ ברחבי ישראל: מהגליל והחרמון בצפון, דרך מדבר יהודה ובקעת הירדן, ועד הנגב בדרום", en:"Found across Israel: from the Galilee and Hermon in the north, through the Judean Desert and Jordan Valley, to the Negev in the south" } },

  { latin:"Eirenis coronelloides", img:"images/unk-14-eirenis-coronelloides.jpg",
    name:{ ar:"الثعبان القزم المخطط", he:"שלוון אזורים", en:"Banded Dwarf Racer" },
    desc:{ ar:"ثعبان صغير ورقيق، بأشرطة عرضية داكنة على طول الجسم.",
           he:"נחש קטן ועדין, בעל פסי רוחב כהים לאורך הגוף.",
           en:"A small, delicate snake with dark crossbands along its body." },
    length:{ ar:"حتى نحو 33–45 سم", he:"עד כ־33–45 ס\"מ", en:"Up to ~33–45 cm" },
    diet:{ ar:"العقارب والعناكب وسائر مفصليات الأرجل", he:"עקרבים, עכבישים ופרוקי־רגליים אחרים", en:"Scorpions, spiders, and other arthropods" },
    range:{ ar:"صحراء يهودا ومنطقة البحر الميت والنقب", he:"מדבר יהודה, אזור ים המלח והנגב", en:"Judean Desert, Dead Sea area, and the Negev" } },

  { latin:"Eirenis rothii", img:"images/unk-15-eirenis-rothii.jpg",
    name:{ ar:"ثعبان روث القزم", he:"שלוון טלוא־ראש", en:"Roth's Dwarf Racer" },
    desc:{ ar:"ثعبان صغير غير سام، برأس داكن ونمط لوني بارز.",
           he:"זהו נחש קטן ולא ארסי, בעל ראש כהה ודגם צבעוני בולט.",
           en:"A small, non-venomous snake with a dark head and a striking color pattern." },
    length:{ ar:"عادةً نحو 30–40 سم", he:"בדרך כלל כ־30–40 ס\"מ", en:"Usually ~30–40 cm" },
    diet:{ ar:"الحشرات والعناكب ومفصليات الأرجل الصغيرة", he:"חרקים, עכבישים ופרוקי־רגליים קטנים", en:"Insects, spiders, and small arthropods" },
    range:{ ar:"شمال إسرائيل ومنطقة صحراء يهودا والبحر الميت", he:"צפון ישראל ואזור מדבר יהודה וים המלח", en:"Northern Israel and the Judean Desert–Dead Sea area" } },

  { latin:"Eirenis lineomaculatus", img:"images/unk-16-eirenis-lineomaculatus.jpg",
    name:{ ar:"الثعبان القزم المرقّط", he:"שלוון כתמים", en:"Narrow-spotted Dwarf Racer" },
    desc:{ ar:"ثعبان صغير، بنّي أو رمادي فاتح غالبًا، مع بقع داكنة على الظهر.",
           he:"נחש קטן, בדרך כלל חום או אפור בהיר, עם כתמים כהים על הגב.",
           en:"A small snake, usually brown or light grey, with dark spots on the back." },
    length:{ ar:"حتى نحو 40 سم، وغالبًا أقل", he:"עד כ־40 ס\"מ, לרוב פחות", en:"Up to ~40 cm, usually less" },
    diet:{ ar:"أساسًا العقارب ومفصليات الأرجل", he:"בעיקר עקרבים ופרוקי־רגליים", en:"Mainly scorpions and arthropods" },
    range:{ ar:"شمال ووسط إسرائيل", he:"צפון ומרכז ישראל", en:"Northern and central Israel" } },

  { latin:"Eirenis decemlineatus", img:"images/unk-17-eirenis-decemlineatus.jpg",
    name:{ ar:"أفعى قزمة بخطوط رفيعة", he:"שלוון קווים", en:"Narrow-striped Dwarf Snake" },
    desc:{ ar:"ثعبان صغير غير سام، جسمه بنّي مصفرّ بخطوط داكنة على طوله.",
           he:"נחש קטן ולא ארסי, בעל גוף חום־צהבהב וקווים כהים לאורך הגוף.",
           en:"A small, non-venomous snake with a yellowish-brown body and dark lines along it." },
    length:{ ar:"حتى نحو 40–45 سم؛ ذكرت مصادر قديمة حتى نحو 85 سم", he:"עד כ־40–45 ס\"מ; מקורות ישנים ציינו עד כ־85 ס\"מ", en:"Up to ~40–45 cm; older sources cited up to ~85 cm" },
    diet:{ ar:"الحشرات والعناكب والسحالي الصغيرة", he:"חרקים, עכבישים ולטאות קטנות", en:"Insects, spiders, and small lizards" },
    range:{ ar:"شمال ووسط إسرائيل", he:"צפון ומרכז ישראל", en:"Northern and central Israel" } },

  { latin:"Eirenis levantinus", img:"images/unk-18-eirenis-levantinus.jpg",
    name:{ ar:"الثعبان القزم ذو الطوق", he:"שלוון קולר", en:"Ring-headed Dwarf Snake" },
    desc:{ ar:"في إسرائيل يرتبط أساسًا بمنطقة الحرمون وشمال البلاد.",
           he:"בישראל הוא מזוהה בעיקר עם אזור החרמון וצפון הארץ.",
           en:"In Israel it is associated mainly with the Hermon area and the north of the country." },
    length:{ ar:"حتى نحو 70 سم", he:"עד כ־70 ס\"מ", en:"Up to ~70 cm" },
    diet:{ ar:"أساسًا الحشرات ومفصليات الأرجل", he:"בעיקר חרקים ופרוקי־רגליים", en:"Mainly insects and arthropods" },
    range:{ ar:"الحرمون وشمال إسرائيل", he:"החרמון וצפון ישראל", en:"Hermon and northern Israel" } },

  { latin:"Rhagerhis moilensis", img:"images/unk-19-rhagerhis-moilensis.jpg",
    name:{ ar:"الحنش الصحراوي المضلّع (الكوبرا الكاذبة)", he:"תלום־קשקשים מדברי", en:"Moila Snake (False Cobra)" },
    desc:{ ar:"عند شعوره بالتهديد يوسّع منطقة العنق ويحاكي إلى حدٍّ ما سلوك الكوبرا. (خلفي الأنياب بسمّ خفيف.)",
           he:"כאשר הוא מרגיש מאוים, הוא מרחיב את אזור הצוואר ומחקה במידה מסוימת התנהגות של קוברה.",
           en:"When threatened, it flattens its neck and somewhat mimics cobra behavior. (Rear-fanged, mildly venomous.)" },
    length:{ ar:"حتى نحو 102 سم", he:"עד כ־102 ס\"מ", en:"Up to ~102 cm" },
    diet:{ ar:"السحالي والثعابين والطيور والقوارض", he:"לטאות, נחשים, ציפורים ומכרסמים", en:"Lizards, snakes, birds, and rodents" },
    range:{ ar:"العربة وجنوب النقب في إسرائيل", he:"הערבה והנגב הדרומי בישראל", en:"The Arava and southern Negev in Israel" } }
];
